"""add action to trend

Revision ID: b74896821d99
Revises: 9f11a4e36090
Create Date: 2025-07-08 13:06:14.962883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b74896821d99'
down_revision: Union[str, Sequence[str], None] = '9f11a4e36090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trend_trade', sa.Column('action_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trend_trade', 'action', ['action_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trend_trade', type_='foreignkey')
    op.drop_column('trend_trade', 'action_id')
    # ### end Alembic commands ###
